### ISSUE TITLE
新しく関数作らなくてもよいのでは？

### ISSUE THREAD

**Issue by c0a2107793** [senbe0/ProjExD#4]
https://github.com/senbe0/ProjExD/blob/9221c10e883edf6b90ba9cd1fc9460131a78d8ee/ex02/calc.py#L20

既存の関数内で実行可能であり、似た分類の機能なので、分けなくていいと感じた。

**Comment by senbe0** [comment]
これは"練習"問題と"課題"問題と区別するために、あえて別の関数を設けてあります！
ご指摘ありがとうございます。
