### ISSUE TITLE
リストにまとめられる文

### ISSUE THREAD

**Issue by c0a2107793** [senbe0/ProjExD#5]
https://github.com/senbe0/ProjExD/blob/02ffef344fbc6c6cfd99c9e9bdcd1c13d0bcc512/ex03/maze.py#L67
多くの画像の参照をしているが、その部分をリストにまとめれば、その部分を省略できると感じた。

**Comment by senbe0** [comment]
確かに。
時間があるときリスト構造で実装してみようと思います!
ご指摘ありがとうございます。
