### ISSUE TITLE
不細工なコード

### ISSUE THREAD

**Issue by c0a2107793** [senbe0/ProjExD#7]
https://github.com/senbe0/ProjExD/blob/f1227bbc4f320423e31e09b2ce2a61dad0de1256/ex04/dodge_bomb.py#L48
コードの関数名が酷似しており、混乱を招くと同時に、このようなコードを書くことによって、不必要にコード全体が長くなっているところが気になりました。

**Comment by senbe0** [comment]
ループ処理で重複を消すべきでした！
時間かかりそうなので、あとあと修正してみます…
ご指摘ありがとうございます!
